#include "clsMyString.h"
int main() {
    cout << "\n\n\t\t\t\t\t\t Undo/Redo Project\n\n";
    clsMyString S1;
    cout << "\nS1 = " << S1.Value << ".\n";
    S1.Value = "Mohammed";
    cout << "\nS1 = " << S1.Value << ".\n";
    S1.Value = "Mohammed2";
    cout << "\nS1 = " << S1.Value << ".\n";
    S1.Value = "Mohammed3";
    cout << "\nS1 = " << S1.Value << ".\n";
    cout << "\n\nUndo:";
    cout << "\n----------\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    cout << "\n\nRedo:";
    cout << "\n----------\n";
    S1.Redo();
    cout << "\nS1 After Redo = " << S1.Value << ".\n";
    S1.Redo();
    cout << "\nS1 After Redo = " << S1.Value << ".\n";
    S1.Redo();
    cout << "\nS1 After Redo = " << S1.Value << ".\n";
    S1.Redo();
    cout << "\nS1 After Redo = " << S1.Value << ".\n";
    S1.Redo();
    cout << "\nS1 After Redo = " << S1.Value << ".\n";
    cout << "\n\nUndo:";
    cout << "\n----------\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    S1.Undo();
    cout << "\nS1 After Undo = " << S1.Value << ".\n";
    return 0;
};